local SettingsModule = {}


SettingsModule.RarityGradient = {
    ["Common"] = game.ReplicatedStorage.AW_Inventory.RarityGradient.Common,
    ["Uncommon"] = game.ReplicatedStorage.AW_Inventory.RarityGradient.Uncommon,
    ["Rare"] = game.ReplicatedStorage.AW_Inventory.RarityGradient.Rare,
    ["Epic"] = game.ReplicatedStorage.AW_Inventory.RarityGradient.Epic,
    ["Legendary"] = game.ReplicatedStorage.AW_Inventory.RarityGradient.Legendary,
}

return SettingsModule
